version: "1.0"
info:
  model: int-scaffold
packages:
- name: WmAmazonAuroraProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
  wpmVersion: v10.1.0
- name: Io_RsaFwk_Utilties_Test
  version: "1.0"
  gitServerName: SomaIBM
  gitUrl: https://github.com/ibm-webmethods
  gitUsername: Somasekhar-K-IBM
  gitBranch: main
- name: ImportTest1Project
  gitServerName: SomaIBM
  gitUrl: https://github.com/Somasekhar-K-IBM
  gitUsername: Somasekhar-K-IBM
  gitBranch: testing
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.importtest1.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:ConnectionTest
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.importtest1.integrations:DafAddInt
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2077
- serviceName: project.importtest1.integrations:DafFlowWithCustomPackage
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: java:addNums
  packages:
  - name: Io_RsaFwk_utilities
    version: "1.0"
- serviceName: project.importtest1.integrations:DafTest1
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2077
- serviceName: project.importtest1.integrations:SalesForceDaf
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.importtest1.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:Account
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
configurationVariables:
  ? iscloudstreamsconnectorservice.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Account.connectionAlias
  : project.importtest1.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:ConnectionTest
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.timeoutType
  : fixed
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.poolable
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cr.authSchemeType
  : basic
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cr.username
  : siqa@swag.com
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.serverRedirectMax
  : "5"
  ? iscloudstreamsconnectorservice.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:Account.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cr.password
  : "{AES}+iHU3riemO8Gm+dAcAtowQ=="
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..importtest1..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:ConnectionTest.cn.keepAliveInterval
  : "300000"
