version: "1.0"
info:
  model: int-scaffold
packages:
- name: ImportTest1Project
  gitServerName: SomaIBM
  gitUrl: https://github.com/Somasekhar-K-IBM
  gitUsername: Somasekhar-K-IBM
  gitBranch: testing
- name: Io_RsaFwk_Utilties_Test
  version: "1.0"
  gitServerName: SomaIBM1
  gitUrl: https://github.com/ibm-webmethods
  gitUsername: Somasekhar-K-IBM
  gitBranch: main
services:
- serviceName: project.importtest1.integrations:DafAddInt
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
- serviceName: project.importtest1.integrations:DafFlowWithCustomPackage
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
- serviceName: java:addNums
  packages:
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
- serviceName: project.importtest1.integrations:DafTest1
  packages:
  - name: ImportTest1Project
    version: "1.0"
  - name: Io_RsaFwk_Utilties_Test
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2055
